src/Entity/Setting.php
<?php

namespace App\Entity;

use App\Repository\SettingRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SettingRepository::class)]
class Setting
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $website_name = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $currency = null;

    #[ORM\Column(nullable: true)]
    private ?int $taxe_rate = null;

    #[ORM\Column(length: 255)]
    private ?string $logo = null;

    #[ORM\Column(length: 255)]
    private ?string $street = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $zip_code = null;

    #[ORM\Column(length: 255)]
    private ?string $state = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(length: 255)]
    private ?string $phone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $facebookLink = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $youtubeLink = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $instaLink = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $copyright = null;

    public function __construct() {
        $this->setCreatedAt(new \DateTimeImmutable ());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getWebsiteName(): ?string
    {
        return $this->website_name;
    }

    public function setWebsiteName(string $website_name): static
    {
        $this->website_name = $website_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    public function setCurrency(string $currency): static
    {
        $this->currency = $currency;

        return $this;
    }

    public function getTaxeRate(): ?int
    {
        return $this->taxe_rate;
    }

    public function setTaxeRate(?int $taxe_rate): static
    {
        $this->taxe_rate = $taxe_rate;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): static
    {
        $this->street = $street;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): static
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): static
    {
        $this->state = $state;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getFacebookLink(): ?string
    {
        return $this->facebookLink;
    }

    public function setFacebookLink(?string $facebookLink): static
    {
        $this->facebookLink = $facebookLink;

        return $this;
    }

    public function getYoutubeLink(): ?string
    {
        return $this->youtubeLink;
    }

    public function setYoutubeLink(?string $youtubeLink): static
    {
        $this->youtubeLink = $youtubeLink;

        return $this;
    }

    public function getInstaLink(): ?string
    {
        return $this->instaLink;
    }

    public function setInstaLink(?string $instaLink): static
    {
        $this->instaLink = $instaLink;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getCopyright(): ?string
    {
        return $this->copyright;
    }

    public function setCopyright(string $copyright): static
    {
        $this->copyright = $copyright;

        return $this;
    }
}

src/Entity/Sliders.php
<?php

namespace App\Entity;

use App\Repository\SlidersRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SlidersRepository::class)]
class Sliders
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $button_text = null;

    #[ORM\Column(length: 255)]
    private ?string $button_link = null;

    #[ORM\Column(length: 255)]
    private ?string $imageUrl = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    public function __construct() {
        $this->setCreatedAt(new \DateTimeImmutable ());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getButtonText(): ?string
    {
        return $this->button_text;
    }

    public function setButtonText(string $button_text): static
    {
        $this->button_text = $button_text;

        return $this;
    }

    public function getButtonLink(): ?string
    {
        return $this->button_link;
    }

    public function setButtonLink(string $button_link): static
    {
        $this->button_link = $button_link;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->imageUrl;
    }

    public function setImageUrl(string $imageUrl): static
    {
        $this->imageUrl = $imageUrl;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }
}

templates/header/header.html.twig
<header class="header_wrap fixed-top header_with_topbar active">
    <div class="top-header" style="">
        <div class="container">
            <div class="row align-item-center">
                <div class="col-md-6">
                    <div class="d-flex align-items-center justify-content-center justify-content-md-start">
                        <ul class="contact_detail text-center text-lg-start">
                            <li><i class="ti-mobile"></i><span>+33 {{ app.session.get("setting").phone }}</span></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="text-center text-md-end">
                        <ul class="header_list">
                            <li><a href="/compare">
                            <i class="ti-control-shuffle"></i><span>Comparer</span>
                            </a></li>

                            <li><a href="/wishlist">
                            <i class="ti-heart"></i><span>Liste de souhaits</span>
                            </a></li>

                            {% if app.user %}
                                <li><a href="/account">
                                    <i class="ti-user"></i><span>Mon compte</span>
                                    </a>
                                </li>
								<li><a href="/logout">
                                    <i class="ti-user"></i><span>Déconnexion</span>
                                    </a>
                                </li>		
							{% else %}
                                <li><a href="/login">
                                    <i class="ti-user"></i><span>Connexion</span>
                                    </a></li>

                                <li><a href="/register">
                                    <i class="ti-user"></i><span>S'enregistrer</span>
                                    </a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom_header dark_skin main_menu_uppercase">
        <div class="container">
            <div class="navbar navbar-expand-lg"> 
                <button type="button" 
                        data-bs-toggle="collapse" 
                        data-bs-target="#navbarSupportedContent" 
                        aria-expanded="false"
                        class="navbar-toggler collapsed">
                        <span class="ion-android-menu"></span>
                </button>
                <a href="/"><h2 class="text-uppercase">{{ app.session.get("setting").websiteName }}</h2></a>
                <div id="navbarSupportedContent" class="navbar-collapse justify-content-end collapse" style="">
                    <ul class="navbar-nav">
                        <li class="dropdown"><a routerlink="/" 
                            class="nav-link" 
                            ng-reflect-router-link="/" 
                            href="/">Accueil</a></li>

                        <li class="dropdown"><a href="#"
                            data-bs-toggle="dropdown" 
                            class="dropdown-toggle nav-link"
                            aria-expanded="false">Pages</a>

                            <div class="dropdown-menu">
                                <ul>
                                    {% for page in app.session.get("headerPages") %}
                                        <li ><a class="dropdown-item nav-link nav_item"
                                                href="/page/{{ page.slug }}">{{ page.title }}
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </li>
                        <li class="dropdown dropdown-mega-menu">
                            <a  href="#" data-bs-toggle="dropdown" 
                                class="dropdown-toggle nav-link" 
                                aria-expanded="false">Produits
                            </a>
                            <div class="dropdown-menu">
                                <ul class="mega-menu d-lg-flex">
                                    {% for category in app.session.get('categories') %}
                                        <li class="mega-menu-col col-lg-3">
                                            <ul>
                                                <li class="dropdown-header">{{ category.name }}</li>
                                                {% for product in category.products %}
                                                    {% if loop.index < 4 %}
                                                        <li >
                                                            <a class="dropdown-item nav-link nav_item"
                                                                href="/product/{{ product.slug }}">
                                                                <img src="/assets/images/produits/{{ product.imageUrls[0] }}"
                                                                    width="50" height="50" alt="">
                                                                {{ product.name }}
                                                            </a>
                                                        </li>
                                                    {% endif %}
                                                {% endfor %}
                                            </ul>
                                        </li>
                                    {% endfor %}
                                </ul>
                                <div class="d-lg-flex menu_banners row g-3 px-3">
                                    {% for collection in app.session.get('megaCollections') %}
                                    <div class="col-sm-4">
                                        <div class="header-banner"><img
                                                alt="menu_banner1"
                                                src="/assets/images/collections/{{ collection.imageUrl }}">
                                            <div class="banne_info mt-4">
                                                <h6>{{ collection.description }}</h6>
                                                <h4>{{ collection.title }}</h4>
                                                <a href="{{ collection.buttonLink }}">{{ collection.buttonText }}</a>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </li>
                        <li class="dropdown dropdown-mega-menu"><a
                                routerlink="/shop-list" 
                                class="nav-link"
                                ng-reflect-router-link="/shop-list" 
                                href="/shop-list">Magasin</a></li>
                        <li ><a routerlink="/contact"
                                class="nav-link nav_item" 
                                ng-reflect-router-link="/contact" 
                                href="/page/contactez-nous">Nous contacter</a>
                        </li>
                    </ul>
                </div>
                <ul class="navbar-nav attr-nav align-items-center">
                    <li><a href="javascript:void(0);"
                        class="nav-link search_trigger"><i 
                        class="linearicons-magnifier"></i></a>

                        <div class="search_wrap"><span 
                                class="close-search"><i 
                                    class="ion-ios-close-empty"></i></span>
                            <form novalidate="" 
                                class="ng-untouched ng-pristine ng-valid">
                                <input type="text" placeholder="Search" id="search_input"
                                    class="form-control">
                                    <button  type="submit"
                                            class="search_icon"><i 
                                            class="ion-ios-search-strong"></i>
                                    </button>
                            </form>
                        </div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                        <div class="search_overlay"></div>
                    </li>
                    <li class="dropdown cart_dropdown">
                        <a href="#" data-bs-toggle="dropdown" class="nav-link cart_trigger">
                            <i class="linearicons-cart"></i>
                            <span class="cart_count"></span> 
                        </a>
                        <div class="cart_box dropdown-menu dropdown-menu-right">
                            <ul class="cart_list">
                                
                            </ul>
                            <div class="cart_footer">
                                <p class="cart_total">
                                    <strong>Total du panier:</strong>
                                    <span class="cart_price">
                                        <span class="price_symbole"></span>
                                    </span>
                                    <span class="cart_price_value">
                                        
                                    </span>
                                </p>
                                <p class="cart_buttons">
                                    <a class="btn btn-fill-line view-cart"
                                        href="/cart">Voir Panier</a>
                                        <a class="btn btn-fill-out checkout" 
                                            href="/checkout">Commander
                                        </a>
                                </p>
                            </div>
                        </div>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>